# Generated by Django 3.1 on 2020-09-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200902_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='count',
        ),
        migrations.AddField(
            model_name='notification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.tweet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='username_assigned',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
